sudo: required
dist: trusty
language: cpp

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt55[QTPACKAGE] qt55webkit

script:
  - source /opt/qt55/bin/qt55-env.sh
  - /opt/qt55/bin/qmake -project
  - /opt/qt55/bin/qmake KBBI-Qt.pro
  - sed -i 's/QtWebKit/QtWebKitWidgets/g' ui_puebi.h
  - make
